### ISSUE TITLE
Rain sounds playing in snowy biome.

### ISSUE THREAD

**Issue by AriRexouium** [CreativeMD/AmbientSounds#154]
When in a snow like biome, sometimes rain sounds are played instead of blizzard sounds when standing in certain positions in the world. I additionally tested AmbientSounds on a fresh instance of Quilt and a fresh instance of Fabric to ensure no other mods interfered. This appears to be a similar or the same issue seen in #115.

![2022-12-18_10 55 33](https://user-images.githubusercontent.com/21180622/208308834-d4c87e6a-160c-41b1-84da-b69acae9b1ca.png)

**Comment by CreativeMD** [comment]
Finally fixed in the newest version. Hope everything is working fine now!

**Comment by designsbyaustin** [comment]
Hey Creative! I absolutely love the mod. I just wanted to tell you that this issue isn't quite fixed. My minecraft home is in a snowy biome and the rain sounds still occur when I am not touching the falling snow.

This happens in my home, as well as anytime I walk under cover or into a small cave. When exiting my home/cave, it makes the rain sound right up until I touch the falling snow. If you need video proof of this, I can provide!

**Comment by CreativeMD** [comment]
@designsbyaustin What version are you using? Furthermore can you use the command /ambient-debug and post some screenshots here? It would make it a lot easier to see what is going on.

**Comment by designsbyaustin** [comment]
I just checked the version, and I am indeed using 5.2.13, the version right before this was fixed. That's my bad. Thank you for the quick reply!
