### ISSUE TITLE
Frequent Orbis-related IllegalStateException errors

### ISSUE THREAD

**Issue by ghost** [CreativeMD/AmbientSounds#235]
Minecraft: 1.21
NeoForge: 21.0.14-beta
Creative Core: 2.11.34
Ambient Sounds: 6.0.2

[Hopefully I picked the right culprit and shouldn't have gone with Tales (aka Creative Core).]

Am seeing a lot of the following errors on an extremely light (2 mod) instance:

```
[17Jun2024 18:04:31.006] [Sound engine/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Sound executor
java.lang.IllegalStateException: Corrupt or missing data in bitstream
        at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.JOrbisAudioStream.readPage(JOrbisAudioStream.java:129) ~[client-1.21-20240613.152323-srg.jar%23171!/:?]
        at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.JOrbisAudioStream.readPacket(JOrbisAudioStream.java:157) ~[client-1.21-20240613.152323-srg.jar%23171!/:?]
        at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.JOrbisAudioStream.readChunk(JOrbisAudioStream.java:192) ~[client-1.21-20240613.152323-srg.jar%23171!/:?]
        at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.FloatSampleSource.read(FloatSampleSource.java:17) ~[client-1.21-20240613.152323-srg.jar%23171!/:?]
[...]
```

Have run the same test instance containing only Abient Sounds and Creative Core a few times and it's 100% reproduceable.

Log from one iteration of that singleplayer world [here](https://gist.github.com/antiphysika/d63203fa0216c3cad334321d2c31f1cf) with the debug.log [here](https://gist.github.com/antiphysika/59ac1e21df0bddc7e7a2d30fb36348bb)

With any luck I'll have not missed any vital detail but please give me a shout if I have. And thanks for the awesome mod!

**Comment by CreativeMD** [comment]
Sorry for responding quite late. This issue is quite weird, because for me it works fine and so far nobody else has ever reported it. Is it still there? Maybe an update of NeoForge fixes it?

**Comment by CreativeMD** [comment]
Any news?

**Comment by tetonis** [comment]
Happening for me on Neoforge version 21.0.130
```
[01/08/2024 02:52:09 AM] java.lang.IllegalStateException: Corrupt or missing data in bitstream
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.JOrbisAudioStream.readPage(JOrbisAudioStream.java:129) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:ambientsounds.mixins.json:OggAudioStreamMixin from mod ambientsounds,pl:mixin:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.JOrbisAudioStream.readPacket(JOrbisAudioStream.java:157) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:ambientsounds.mixins.json:OggAudioStreamMixin from mod ambientsounds,pl:mixin:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.JOrbisAudioStream.readChunk(JOrbisAudioStream.java:192) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:ambientsounds.mixins.json:OggAudioStreamMixin from mod ambientsounds,pl:mixin:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.FloatSampleSource.read(FloatSampleSource.java:17) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:computing_frames,re:mixin,re:classloading}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.LoopingAudioStream.read(LoopingAudioStream.java:41) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:computing_frames,re:classloading}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.audio.Channel.pumpBuffers(Channel.java:151) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,re:classloading,pl:mixin:APP:sound_physics_remastered.mixins.json:SourceMixin from mod (unknown),pl:mixin:APP:sound_physics_remastered.mixins.json:ChannelAccessor from mod (unknown),pl:mixin:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.audio.Channel.attachBufferStream(Channel.java:140) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,re:classloading,pl:mixin:APP:sound_physics_remastered.mixins.json:SourceMixin from mod (unknown),pl:mixin:APP:sound_physics_remastered.mixins.json:ChannelAccessor from mod (unknown),pl:mixin:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.SoundEngine.lambda$play$8(SoundEngine.java:410) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sound_physics_remastered.mixins.json:SoundSystemMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.ChannelAccess$ChannelHandle.lambda$execute$0(ChannelAccess.java:34) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,re:classloading}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
[01/08/2024 02:52:09 AM] 	at TRANSFORMER/minecraft@1.21/net.minecraft.client.sounds.SoundEngineExecutor.run(SoundEngineExecutor.java:42) ~[client-1.21-20240613.152323-srg.jar%23279!/:?] {re:classloading}
[01/08/2024 02:52:09 AM] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
```

**Comment by tetonis** [comment]
I'm not sure if this is related but I'm also experiencing issue #228 on AmbientSounds 6.0.4 even though you said it was fixed.

**Comment by CreativeMD** [comment]
It's quite a weird bug. Seems like nobody else has this issue. Not sure what I can do about this. I cannot reproduce this issue and it works fine for all the others. Maybe some sound files got corrupted. Maybe try to reinstall Minecraft?

**Comment by ghost** [comment]
Ach. Sorry for coming back to the party so late, I was relying on GitHub's notifications not to be jank. Apparently I need to check my e-mail more often...

I'm pretty sure I still have the instance around where this bug cropped up. I'll go hunt it down and see if I can still easily reproduce and report back what I find.

**Comment by ghost** [comment]
Good news (or bad depending on your pov :stuck_out_tongue:). I can reproduce this with just Neo `21.1.42` and AmbientSounds `6.0.6` with CreativeCore `2.12.11`.

If I can be of any help tracking this down, I'm game. Could easily have a dev env setup in short order as well. I'll try and keep a more thorough eye on my e-mail this time but, in case I miss something, I'm on the Neo server, same username as here and not averse to pings.

**Comment by CreativeMD** [comment]
Hey, thanks for responding again. Someone else reported the same issue here:

It took quite some time, but it is finally fixed and has been released. Thanks for taking the time, hope everything works fine for you now!
